# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee4c75077f8e698c662306da2138767c322137c5421b7c221f90c3df5b88d9f3564e85cb3db91d24b6bbb766bf20a7a3941559b8fc45b33f7f72a894867b0cf0

test:
  secret_key_base: 0af52ac2c1d39ac6ac0561aeb15277d2ae14f843b087cea9e72131e4f7f6cefc3bbf77a95e5796b32e50d3c8b87b2f29d9b4ac798746bfc1f4eee186b34a1740

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
